### ISSUE TITLE
Running-cue Related Time Variables in Timeline Groups

### ISSUE THREAD

**Issue by techdave84** [bitfocus/companion-module-figure53-qlab-advance#105]
Q-Lab 5.2.4
Companion 3.1.1
QLabFb v2.2.2

Possibly I need to change how I build my shows but I like to use a group to mark out a section of a show. For example, 'Session 1' 'Session 2' 'Awards' 'Day 1' 'Day 5' and have the audio cues I need for that block in Timeline order. Typically group would contain a small number of musical walkup/award stings to be played one at a time when required.

The string $(qlabfb:r_left) works fine for audio cues that are not in a group.  If you move the same cue into a group and you get '00' as your feedback until you hit the longest cue in the group, then it displays the full remaining time and does not count down.
If you play the Group as a cue it gives the countdown to the end of the timeline.

I presume the fix for this is to change my workflow, is there an alternative way to mark different sections of a show?

**Comment by istnv** [comment]
Since QLab can actually 'run' dozens of cues at once, there will always be the problem of finding the 'One best cue' for the dynamic 'running cue' variables. 
When asked for the current 'Active/Running' cues, QLab returns all running cues, as well as the parent group, cue list, and workspace. They are all considered active, but not all have useable 'times'.

QLab5 adds a couple of new cue status flags that may help narrow down which cue would be best. 

Until that is implemented, I have done something like this:
![image](https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/51003420/6891df14-915f-4d75-a6fa-88d8fbb98b89)

Create a Memo cue with a stand-out title and color: '===== Day 1 ========', orange
and leave the audio stingers as individual cues.

Another way is to create a different cue list for each segment/session.

**Comment by techdave84** [comment]
See, I knew there would be a better way of doing things.  Memos now added to my workflow.
Going to close this, as it was mostly a user error.

> Since QLab can actually 'run' dozens of cues at once, there will always be the problem of finding the 'One best cue' for the dynamic 'running cue' variables. When asked for the current 'Active/Running' cues, QLab returns all running cues, as well as the parent group, cue list, and workspace. They are all considered active, but not all have useable 'times'.

This is the useful-to-know bit.  Thanks.
