### ISSUE TITLE
[Feature Request] Override Controls - OSC Output

### ISSUE THREAD

**Issue by jbilyj** [bitfocus/companion-module-figure53-qlab-advance#46]
It would be great to be able to control the Override Controls - mainly the OSC Output Override. OSC is just /overrides/oscOutputEnabled {number}. 0 being false, 1 being true. Mainly useful when running main/backup systems.

**Comment by istnv** [comment]
That disables a lot of information the module depends on for cue status. How are you configuring your commands and feedback for the backup?

**Comment by jbilyj** [comment]
We run a custom script to playback cues along with having physical buttons for activations. For those physical buttons, main and backup are triggered at the same time. We generally don't use feedback for the physical buttons being there is no 'colour for cue running' feedback. Within the cue lists we have a few OSC cues triggering other QLAB machines hence we don't want those machines receiving double commands

The plan is to have seperate buttons to switch between Mac Main and Mac Backup should there be an issue. Currently we're just using the overrides window.

Mac Main: Enable OSC Output (MacM), Disable OSC Output (MacB)
Mac Backup: Enable OSC Output (MacB), Disable OSC Output (MacM)

Obviously being able to Disable/Enable OSC Output has a limited use case but it would be extremely useful.

**Comment by istnv** [comment]
Thank you for responding. That is the second mention this week of 'color for cue running'. This module has more dynamic variables than some others. There is a dynamic variable for both playhead and running cue that shows Cue Status: "✕" if broken, "⏽" if loaded, "⏵" if running, "⏸" if paused, otherwise "·".

_I'm thinking out loud here for a moment_
The module keeps an internal copy of the cuelist ids, numbers, names, and status which stays consistent because of  QLab notifications. That list will be out of sync if OSC output is disabled. 
The only real black hole is when OSC input is disabled as QLab ignores any requests. When OSC output is disabled, it still responds when asked about the OSC output override. The module will need to detect this and fall back to a 'limited' mode.

I'll look into this when I have some time.

**Comment by istnv** [comment]
I took another look at this. When OSC output is disabled, QLab still sends updates to Companion, so there may not be a need for a 'limited' mode. I will probably add a toggle for each override (except OSC listen).

@jbilyj :
> there is no 'colour for cue running' feedback.
Can you describe what this would be?

**Comment by jbilyj** [comment]
Thanks for the update. Colour for Cue Running would be great for when you run carts. Being able to set the background colour if the selected qnum is running, would be extremely useful. Let me know if you need anything else.
